### PR TITLE
Fix #937 bolt-socket-mode establishes a connection before a SocketModeApp#start()/startAsync() method call

### LINKED ISSUE #937: bolt-socket-mode establishes a connection before a SocketModeApp#start()/startAsync() method call
The following code has not yet started the `socketModeApp`.

```java
var app = new App(AppConfig.builder().singleTeamBotToken(System.getenv("SLACK_BOT_TOKEN")).build());
var socketModeApp = new SocketModeApp(System.getenv("SLACK_APP_TOKEN"), app);
// socketModeApp.start();
Thread.sleep(Long.MAX_VALUE);
```

However, the log outputs says:

```
2022-02-18 07:00:58,834 INFO [socket-mode-session-monitor-worker-39] com.slack.api.socket_mode.SocketModeClient The current session is no longer active. Going to reconnect to the Socket Mode server.
2022-02-18 07:00:59,756 INFO [Grizzly(1)] com.slack.api.socket_mode.SocketModeClient New session is open (session id: b3a24a85-3505-4fc5-93ea-7db775496406)
```

This is due to the default behavior of the underlying `SocketModeClient`. However, this is an unexpected behavior for bolt-java users and that should be improved in future releases.

### Reproducible in:

Any versions

#### The Slack SDK version

v1.19.0

#### Java Runtime version

any

#### OS info

any

#### Steps to reproduce:

See the description

### PR DESCRIPTION
**Pull request by seratch**
This pull request resolves #937 

### Category (place an `x` in each of the `[ ]`)

* [ ] **bolt** (Bolt for Java)
* [x] **bolt-{sub modules}** (Bolt for Java - optional modules)
* [ ] **slack-api-client** (Slack API Clients)
* [ ] **slack-api-model** (Slack API Data Models)
* [ ] **slack-api-*-kotlin-extension** (Kotlin Extensions for Slack API Clients)
* [ ] **slack-app-backend** (The primitive layer of Bolt for Java)

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to the those rules.

### CODE REVIEW

File: bolt-socket-mode/src/main/java/com/slack/api/bolt/socket_mode/SocketModeApp.java [hunk 1]
```diff
@@ -14,57 +14,68 @@
 import java.io.IOException;
 import java.util.HashMap;
 import java.util.Map;
+import java.util.function.Supplier;
 
 @Slf4j
 public class SocketModeApp {
-    private boolean clientStopped = false;
-    private final SocketModeClient client;
+    private boolean clientStopped = true;
```
Comment (seratch) [inline bolt-socket-mode/src/main/java/com/slack/api/bolt/socket_mode/SocketModeApp.java:21]: The default state needs to be corrected.

**Review by mwbrooks — APPROVED** [review]
LGTM 🎉
