### PR TITLE
Fix non-closed response bug in bolt-ktor package

### LINKED ISSUE #730: Slow event handling on Ktor framework
Hi! I'm writing service for CI automation, and now I'm about to integrate it with existing Ktor application, but it's very, very slow and I don't understand why. It produces response for >2 seconds! Currently I'm using microservice approach, where chatbot and main service are separate servers (Jetty on bolt, Ktor on the main app), but anyway I'm curious why I got this situation.

I have next questions:

* Is it because Slack with Ktor doesn't work well?
* Or it's Kotlin Coroutines behaviour?
* Or it's about Netty?

When I'll have spare time, I try to answer these questions by myself. But if you have it now, you can look at this :)

### Reproducible in:

```bash
mvn dependency:tree | grep com.slack.api
gradle dependencies | grep com.slack.api
java -version
sw_vers && uname -v # or `ver`
```

#### The Slack SDK version

1.7.1

#### Java Runtime version

1.8.0_282

#### OS info

openSUSE Leap 15.2 (Linux Kernel 5.10.25-2.ge8f7993-default)

#### Steps to reproduce:

Consider we have next dependencies:
```
// build.gradle.kts
dependencies {
    implementation(kotlin("stdlib-jdk8"))
    implementation("ch.qos.logback:logback-classic:1.2.3")
    implementation("com.slack.api:bolt:1.7.1")
    implementation("com.slack.api:bolt-ktor:1.7.1")
    val ktorVersion = "1.5.2"
    implementation("io.ktor:ktor:$ktorVersion")
    implementation("io.ktor:ktor-server-netty:$ktorVersion")
}
```

And this main function:
```kotlin
import com.slack.api.bolt.App
import com.slack.api.bolt.ktor.respond
import com.slack.api.bolt.ktor.toBoltRequest
import com.slack.api.bolt.util.SlackRequestParser
import com.slack.api.model.event.MessageEvent
import io.ktor.application.*
import io.ktor.routing.*
import io.ktor.server.engine.*
import io.ktor.server.netty.*

fun main() {
    val app = App()
    val requestParser = SlackRequestParser(app.config())
    app.event(MessageEvent::class.java) { payload, ctx ->
        if (payload.event.text == "ping") {
            ctx.client().chatPostMessage { it
                .channel(ctx.channelId)
                .text("BONK")
            }
        }
        ctx.ack()
    }
    app.start()
    val server = embeddedServer(Netty, port = 8080) {
        routing {
            post("/slack/events") {
                val request = toBoltRequest(call, requestParser)
                val response = app.run(request)
                respond(call, response)
            }
        }
    }
    server.start(wait = true)
}
```

#### Expected result:

I expected that request handling will take same or less time. Like, if I rewrite this example on top of bolt-jetty, it will take ~0.5 seconds on my machine.

#### Actual result:

But in fact respond is produced only after ~2.93 seconds.

### Requirements

Please make sure if this topic is specific to this SDK. For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to the those rules.

### PR DESCRIPTION
**Pull request by kam1sh**
* Fix bug when bolt's empty ctx.ack() resulted in response that was not
  closed properly
* Also add check for that situation by content-length header check
  in one of the existing tests

This PR closes #730 -- I discovered that if you call `ctx.ack()` on any event handling, then response would only partial (only status code), also not being closed. Tests didn't checked that, I guess because of Ktor test engine behaviour, so I added check for least for content-length header.

### Category (place an `x` in each of the `[ ]`)

* [ ] **bolt** (Bolt for Java)
* [x] **bolt-ktor** (Bolt for Java - optional modules)
* [ ] **slack-api-client** (Slack API Clients)
* [ ] **slack-api-model** (Slack API Data Models)
* [ ] **slack-api-*-kotlin-extension** (Kotlin Extensions for Slack API Clients)
* [ ] **slack-app-backend** (The primitive layer of Bolt for Java)

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to the those rules.

### CODE REVIEW

**Comment by kam1sh** [comment]
Umm... The build is failing because of network error :(

https://github.com/slackapi/java-slack-sdk/pull/732/checks?check_run_id=2404492570#step:4:1455

I didn't worked with GitHub Actions. How can I restart build?..

**Comment by seratch** [comment]
@kam1sh Thanks for making this PR!

>How can I restart build?..

I just manually reran the build. Let's see how it goes.

File: bolt-ktor/src/main/kotlin/com/slack/api/bolt/ktor/package.kt [hunk 1]
```diff
@@ -33,8 +33,8 @@ suspend fun respond(call: ApplicationCall, boltResponse: Response) {
             call.response.header(header.key, value)
         }
     }
-    call.response.status(HttpStatusCode.fromValue(boltResponse.statusCode))
+    val status = HttpStatusCode.fromValue(boltResponse.statusCode)
     if (boltResponse.body != null) {
-        call.respond(TextContent(boltResponse.body, ContentType.parse(boltResponse.contentType)))
-    }
+        call.respondText(boltResponse.body, ContentType.parse(boltResponse.contentType), status)
```
Comment (seratch) [inline bolt-ktor/src/main/kotlin/com/slack/api/bolt/ktor/package.kt:38]: This should work but I slightly prefer using `respond` for both. What do you think?

```kotlin
    val status = HttpStatusCode.fromValue(boltResponse.statusCode)
    if (boltResponse.body != null) {
        val message = TextContent(boltResponse.body, ContentType.parse(boltResponse.contentType))
        call.respond(status, message)
    } else {
        call.respond(status)
    }
```

Comment (kam1sh) [reply bolt-ktor/src/main/kotlin/com/slack/api/bolt/ktor/package.kt:38]: Sure, I can rewrite that piece. One minute.

Comment (kam1sh) [reply bolt-ktor/src/main/kotlin/com/slack/api/bolt/ktor/package.kt]: Look. Is it better now?

Comment (seratch) [reply bolt-ktor/src/main/kotlin/com/slack/api/bolt/ktor/package.kt]: Thanks! LGTM

**Review by seratch — APPROVED** [review]

**Comment by seratch** [comment]
@kam1sh Thanks for your contribution 🎉 We haven't decided when to release the next minor version. Until the release, please use your own implementation as a workaround 🙇
