### PR TITLE
Fix some gaps from other Bolt frameworks

### LINKED ISSUE #572: How to get appId in the saveInstallerAndBot function
Hi. Thanks for the SDK, it's a great tool for building Slack apps. 
I'm currently trying to get the multi-workspace oauth flow running. Because of our project specifics we want to use the Java SDK (this repo) to generate the installation URL (which is already done) and save the Slack org's credentials in DynamoDB upon successful authorization. Then the other part of the Slack app will be hosted in a NodeJS app using the Slack bolt-js SDK (which is already done) which on his part will read the installations from Dynamo. One problem I have with this setup is that when I read the [Installation](https://github.com/slackapi/node-slack-sdk/blob/main/packages/oauth/src/index.ts#L476) object in the NodeJS app, it expects to have the appId field, which I don't have in the [Java Installer object](https://github.com/slackapi/java-slack-sdk/blob/a973bb43db9c1b6136873f3129252dba63315110/bolt/src/main/java/com/slack/api/bolt/model/builtin/DefaultInstaller.java). Is there a way I get my hands on the App Id in my implementation of the [InstallationService](https://github.com/slackapi/java-slack-sdk/blob/main/bolt/src/main/java/com/slack/api/bolt/service/InstallationService.java)?
Thanks

#### The Slack SDK version

[INFO] +- com.slack.api:bolt:jar:1.2.0-SNAPSHOT:compile
[INFO] |  +- com.slack.api:slack-api-model:jar:1.2.0-SNAPSHOT:compile
[INFO] |  +- com.slack.api:slack-api-client:jar:1.2.0-SNAPSHOT:compile
[INFO] |  \- com.slack.api:slack-app-backend:jar:1.2.0-SNAPSHOT:compile
[INFO] +- com.slack.api:bolt-servlet:jar:1.2.0-SNAPSHOT:compile

#### Java Runtime version

openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-8u265-b01-0ubuntu2~20.04-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)

#### OS info

#51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., pom.xml/build.gradle))

1. Hit the installation url
2. Authorize the app in your workspace
3. Enter in the saveInstallerAndBot method in my implementation of the [InstallationService](https://github.com/slackapi/java-slack-sdk/blob/main/bolt/src/main/java/com/slack/api/bolt/service/InstallationService.java)

#### Expected result:

Have the appId in the [Installer object](https://github.com/slackapi/java-slack-sdk/blob/a973bb43db9c1b6136873f3129252dba63315110/bolt/src/main/java/com/slack/api/bolt/model/builtin/DefaultInstaller.java)

#### Actual result:

No appId :upside_down_face:

### PR DESCRIPTION
**Pull request by seratch**
This pull request fixes a few gaps from other Bolt frameworks. We're not aiming to completely remove such differences but the changes in this PR are all backward compatible. So, v1.2 is good timing to introduce these.

Also, this PR fixes #572 

### Category (place an `x` in each of the `[ ]`)

* [x] **bolt** (Bolt for Java)
* [ ] **bolt-{sub modules}** (Bolt for Java - optional modules)
* [ ] **slack-api-client** (Slack API Clients)
* [ ] **slack-api-model** (Slack API Data Models)
* [ ] **slack-api-*-kotlin-extension** (Kotlin Extensions for Slack API Clients)
* [ ] **slack-app-backend** (The primitive layer of Bolt for Java)

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to the those rules.

### CODE REVIEW

File: bolt/src/main/java/com/slack/api/bolt/App.java [hunk 1]
```diff
@@ -68,6 +72,16 @@
      */
     private final Slack slack;
 
+    /**
+     * The default Web API client without any tokens.
+     */
+    private final MethodsClient client;
```
Comment (seratch) [inline bolt/src/main/java/com/slack/api/bolt/App.java:78]: This is equivalent to `app.client` in Bolt for JS.

File: bolt/src/main/java/com/slack/api/bolt/App.java [hunk 2]
```diff
@@ -68,6 +72,16 @@
...
+
+    /**
+     * The built-in handy way to run operations asynchronously. It's totally fine to use your own one instead.
+     */
+    private final ExecutorService executorService;
```
Comment (seratch) [inline bolt/src/main/java/com/slack/api/bolt/App.java:83]: In Java, we should enable developers to use their own runtime for async executions. That said, a built-in handy way is helpful for many. So, we introduce ExecutorService as an option since v1.2.

File: bolt/src/main/java/com/slack/api/bolt/App.java [hunk 3]
```diff
@@ -93,7 +107,18 @@
         if (appConfig.isDistributedApp()) {
             middlewareList.add(new MultiTeamsAuthorization(config(), installationService));
         } else if (appConfig.getSingleTeamBotToken() != null) {
-            middlewareList.add(new SingleTeamAuthorization(config(), installationService));
+            try {
+                AuthTestResponse initialAuthTest = client().authTest(r -> r.token(appConfig.getSingleTeamBotToken()));
+                if (initialAuthTest == null || !initialAuthTest.isOk()) {
+                    String error = initialAuthTest != null ? initialAuthTest.getError() : "";
+                    String message = "The token is invalid (auth.test error: " + error + ")";
+                    throw new IllegalArgumentException(message);
```
Comment (seratch) [inline bolt/src/main/java/com/slack/api/bolt/App.java:115]: SingleTeamAuthorization should throw an exception for an invalid token when booting. This is consistent behavior with Bolt JS and Python.

File: bolt/src/main/java/com/slack/api/bolt/AppConfig.java [hunk 4]
```diff
@@ -29,14 +29,34 @@ private EnvVariableName() {
         public static final String SLACK_BOT_TOKEN = "SLACK_BOT_TOKEN";
         public static final String SLACK_SIGNING_SECRET = "SLACK_SIGNING_SECRET";
         public static final String SLACK_VERIFICATION_TOKEN = "SLACK_VERIFICATION_TOKEN";
+
+        public static final String SLACK_CLIENT_ID = "SLACK_CLIENT_ID";
```
Comment (seratch) [inline bolt/src/main/java/com/slack/api/bolt/AppConfig.java:33]: Change the default env variable names to align with Bolt JS/Python. The old ones are still live.

File: bolt/src/main/java/com/slack/api/bolt/AppConfig.java [hunk 5]
```diff
@@ -69,25 +89,30 @@ public boolean isDistributedApp() {
     @Builder.Default
     private boolean oAuthCallbackEnabled = false;
 
-
     /**
-     * Returns true if auth.test call result cache in SingleTeamAuthorization or MultiTeamsAuthorization middleware
```
Comment (seratch) [inline bolt/src/main/java/com/slack/api/bolt/AppConfig.java:74]: Make this cache mechanism the default for SingleTeamAuthorization.

File: bolt/src/main/java/com/slack/api/bolt/model/Bot.java [hunk 6]
```diff
@@ -5,6 +5,10 @@
  */
 public interface Bot {
 
+    String getAppId();
```
Comment (seratch) [inline bolt/src/main/java/com/slack/api/bolt/model/Bot.java:8]: Fixes #572

File: bolt/src/main/java/com/slack/api/bolt/service/builtin/oauth/default_impl/OAuthDefaultSuccessHandler.java [hunk 7]
```diff
@@ -37,6 +37,7 @@ public Response handle(OAuthCallbackRequest request, Response response, OAuthAcc
         context.setRequestUserToken(o.getAccessToken());
 
         DefaultInstaller.DefaultInstallerBuilder i = DefaultInstaller.builder()
+                .appId(null)
```
Comment (seratch) [inline bolt/src/main/java/com/slack/api/bolt/service/builtin/oauth/default_impl/OAuthDefaultSuccessHandler.java:40]: v1 OAuth API response doesn't provide api_app_id.

File: bolt/src/test/java/test_locally/app/SingleTeamAuthTestCacheTest.java [hunk 8]
```diff
@@ -141,40 +102,6 @@ public void permanentCacheEnabled() throws Exception {
         assertEquals(200L, response.getStatusCode().longValue());
     }
 
-    @Test
```
Comment (seratch) [inline bolt/src/test/java/test_locally/app/SingleTeamAuthTestCacheTest.java:144]: This test is no longer required (there is no option to disable the cache)

**Review by seratch — COMMENTED** [review]
comments for reviewers
