### PR TITLE
Fix #715 - add team property to TeamInfoRequest

### LINKED ISSUE #715: TeamInfoRequest is missing the optional team argument
Hi @seratch,

I believe the TeamInfoRequest class is missing the optional `team` argument [documented here](https://api.slack.com/methods/team.info#arg_team). Because off that, I'm unable to call `methodsAsync().teamInfo` for teams other than my current team. Let me know if I'm not using this method properly. Thanks!

#### The Slack SDK version

```
+--- com.slack.api:bolt:1.7.0
|    +--- com.slack.api:slack-api-model:1.7.0
|    +--- com.slack.api:slack-api-client:1.7.0
|    |    +--- com.slack.api:slack-api-model:1.7.0 (*)
|    \--- com.slack.api:slack-app-backend:1.7.0
|         +--- com.slack.api:slack-api-model:1.7.0 (*)
|         +--- com.slack.api:slack-api-client:1.7.0 (*)
+--- com.slack.api:slack-api-client:1.7.0 (*)
+--- com.slack.api:slack-api-model-kotlin-extension:1.7.0
|    +--- com.slack.api:slack-api-model:1.7.0 (*)
+--- com.slack.api:slack-api-client-kotlin-extension:1.7.0
|    +--- com.slack.api:slack-api-model-kotlin-extension:1.7.0 (*)
|    +--- com.slack.api:slack-api-client:1.7.0 (*)
+--- com.slack.api:bolt-servlet:1.7.0
|    +--- com.slack.api:slack-api-model:1.7.0 (*)
|    +--- com.slack.api:slack-api-client:1.7.0 (*)
|    +--- com.slack.api:slack-app-backend:1.7.0 (*)
|    \--- com.slack.api:bolt:1.7.0 (*)
+--- com.slack.api:bolt:1.7.0 (n)
+--- com.slack.api:slack-api-client:1.7.0 (n)
+--- com.slack.api:slack-api-model-kotlin-extension:1.7.0 (n)
+--- com.slack.api:slack-api-client-kotlin-extension:1.7.0 (n)
+--- com.slack.api:bolt-servlet:1.7.0 (n)
+--- com.slack.api:bolt:1.7.0
|    +--- com.slack.api:slack-api-model:1.7.0
|    +--- com.slack.api:slack-api-client:1.7.0
|    |    +--- com.slack.api:slack-api-model:1.7.0 (*)
|    \--- com.slack.api:slack-app-backend:1.7.0
|         +--- com.slack.api:slack-api-model:1.7.0 (*)
|         +--- com.slack.api:slack-api-client:1.7.0 (*)
+--- com.slack.api:slack-api-client:1.7.0 (*)
+--- com.slack.api:slack-api-model-kotlin-extension:1.7.0
|    +--- com.slack.api:slack-api-model:1.7.0 (*)
+--- com.slack.api:slack-api-client-kotlin-extension:1.7.0
|    +--- com.slack.api:slack-api-model-kotlin-extension:1.7.0 (*)
|    +--- com.slack.api:slack-api-client:1.7.0 (*)
+--- com.slack.api:bolt-servlet:1.7.0
|    +--- com.slack.api:slack-api-model:1.7.0 (*)
|    +--- com.slack.api:slack-api-client:1.7.0 (*)
|    +--- com.slack.api:slack-app-backend:1.7.0 (*)
|    \--- com.slack.api:bolt:1.7.0 (*)
+--- com.slack.api:bolt:1.7.0
|    +--- com.slack.api:slack-api-model:1.7.0
|    +--- com.slack.api:slack-api-client:1.7.0
|    |    +--- com.slack.api:slack-api-model:1.7.0 (*)
|    \--- com.slack.api:slack-app-backend:1.7.0
|         +--- com.slack.api:slack-api-model:1.7.0 (*)
|         +--- com.slack.api:slack-api-client:1.7.0 (*)
+--- com.slack.api:slack-api-client:1.7.0 (*)
+--- com.slack.api:slack-api-model-kotlin-extension:1.7.0
|    +--- com.slack.api:slack-api-model:1.7.0 (*)
+--- com.slack.api:slack-api-client-kotlin-extension:1.7.0
|    +--- com.slack.api:slack-api-model-kotlin-extension:1.7.0 (*)
|    +--- com.slack.api:slack-api-client:1.7.0 (*)
+--- com.slack.api:bolt-servlet:1.7.0
|    +--- com.slack.api:slack-api-model:1.7.0 (*)
|    +--- com.slack.api:slack-api-client:1.7.0 (*)
|    +--- com.slack.api:slack-app-backend:1.7.0 (*)
|    \--- com.slack.api:bolt:1.7.0 (*)
+--- com.slack.api:bolt:1.7.0
|    +--- com.slack.api:slack-api-model:1.7.0
|    +--- com.slack.api:slack-api-client:1.7.0
|    |    +--- com.slack.api:slack-api-model:1.7.0 (*)
|    \--- com.slack.api:slack-app-backend:1.7.0
|         +--- com.slack.api:slack-api-model:1.7.0 (*)
|         +--- com.slack.api:slack-api-client:1.7.0 (*)
+--- com.slack.api:slack-api-client:1.7.0 (*)
+--- com.slack.api:slack-api-model-kotlin-extension:1.7.0
|    +--- com.slack.api:slack-api-model:1.7.0 (*)
+--- com.slack.api:slack-api-client-kotlin-extension:1.7.0
|    +--- com.slack.api:slack-api-model-kotlin-extension:1.7.0 (*)
|    +--- com.slack.api:slack-api-client:1.7.0 (*)
+--- com.slack.api:bolt-servlet:1.7.0
|    +--- com.slack.api:slack-api-model:1.7.0 (*)
|    +--- com.slack.api:slack-api-client:1.7.0 (*)
|    +--- com.slack.api:slack-app-backend:1.7.0 (*)
|    \--- com.slack.api:bolt:1.7.0 (*)
+--- com.slack.api:bolt:1.7.0
|    +--- com.slack.api:slack-api-model:1.7.0
|    +--- com.slack.api:slack-api-client:1.7.0
|    |    +--- com.slack.api:slack-api-model:1.7.0 (*)
|    \--- com.slack.api:slack-app-backend:1.7.0
|         +--- com.slack.api:slack-api-model:1.7.0 (*)
|         +--- com.slack.api:slack-api-client:1.7.0 (*)
+--- com.slack.api:slack-api-client:1.7.0 (*)
+--- com.slack.api:slack-api-model-kotlin-extension:1.7.0
|    +--- com.slack.api:slack-api-model:1.7.0 (*)
+--- com.slack.api:slack-api-client-kotlin-extension:1.7.0
|    +--- com.slack.api:slack-api-model-kotlin-extension:1.7.0 (*)
|    +--- com.slack.api:slack-api-client:1.7.0 (*)
+--- com.slack.api:bolt-servlet:1.7.0
|    +--- com.slack.api:slack-api-model:1.7.0 (*)
|    +--- com.slack.api:slack-api-client:1.7.0 (*)
|    +--- com.slack.api:slack-app-backend:1.7.0 (*)
|    \--- com.slack.api:bolt:1.7.0 (*)
+--- com.slack.api:bolt:1.7.0
|    +--- com.slack.api:slack-api-model:1.7.0
|    +--- com.slack.api:slack-api-client:1.7.0
|    |    +--- com.slack.api:slack-api-model:1.7.0 (*)
|    \--- com.slack.api:slack-app-backend:1.7.0
|         +--- com.slack.api:slack-api-model:1.7.0 (*)
|         +--- com.slack.api:slack-api-client:1.7.0 (*)
+--- com.slack.api:slack-api-client:1.7.0 (*)
+--- com.slack.api:slack-api-model-kotlin-extension:1.7.0
|    +--- com.slack.api:slack-api-model:1.7.0 (*)
+--- com.slack.api:slack-api-client-kotlin-extension:1.7.0
|    +--- com.slack.api:slack-api-model-kotlin-extension:1.7.0 (*)
|    +--- com.slack.api:slack-api-client:1.7.0 (*)
+--- com.slack.api:bolt-servlet:1.7.0
|    +--- com.slack.api:slack-api-model:1.7.0 (*)
|    +--- com.slack.api:slack-api-client:1.7.0 (*)
|    +--- com.slack.api:slack-app-backend:1.7.0 (*)
|    \--- com.slack.api:bolt:1.7.0 (*)
+--- com.slack.api:bolt:1.7.0
|    +--- com.slack.api:slack-api-model:1.7.0
|    +--- com.slack.api:slack-api-client:1.7.0
|    |    +--- com.slack.api:slack-api-model:1.7.0 (*)
|    \--- com.slack.api:slack-app-backend:1.7.0
|         +--- com.slack.api:slack-api-model:1.7.0 (*)
|         +--- com.slack.api:slack-api-client:1.7.0 (*)
+--- com.slack.api:slack-api-client:1.7.0 (*)
+--- com.slack.api:slack-api-model-kotlin-extension:1.7.0
|    +--- com.slack.api:slack-api-model:1.7.0 (*)
+--- com.slack.api:slack-api-client-kotlin-extension:1.7.0
|    +--- com.slack.api:slack-api-model-kotlin-extension:1.7.0 (*)
|    +--- com.slack.api:slack-api-client:1.7.0 (*)
+--- com.slack.api:bolt-servlet:1.7.0
|    +--- com.slack.api:slack-api-model:1.7.0 (*)
|    +--- com.slack.api:slack-api-client:1.7.0 (*)
|    +--- com.slack.api:slack-app-backend:1.7.0 (*)
|    \--- com.slack.api:bolt:1.7.0 (*)
```

#### Java Runtime version

```
openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment (build 15.0.1+9-18)
OpenJDK 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)
```

#### OS info

```
ProductName:	macOS
ProductVersion:	11.2.3
BuildVersion:	20D91
Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64
```

#### Steps to reproduce:

```
import com.slack.api.methods.MethodsClient;
import com.slack.api.methods.request.chat.ChatPostMessageRequest;
import com.slack.api.methods.response.chat.ChatPostMessageResponse;

val slack = Slack.getInstance()
val token = 'SLACK-TOKEN'
slack.methods().teamInfo { it.token(token).team('T00000000') }

```
#### Expected result:

team.info is called and returns the details of the team T00000000

#### Actual result:

teamInfo doesn't have a team property 

### Requirements

Please make sure if this topic is specific to this SDK. For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to the those rules.

### PR DESCRIPTION
**Pull request by lfbrandao**
Add `team` property to `TeamInfoRequest`. This property is currently missing on the SDK, but is documented [on the API docs](https://api.slack.com/methods/team.info#arg_team).

### Category (place an `x` in each of the `[ ]`)

* [ ] **bolt** (Bolt for Java)
* [ ] **bolt-{sub modules}** (Bolt for Java - optional modules)
* [x ] **slack-api-client** (Slack API Clients)
* [ ] **slack-api-model** (Slack API Data Models)
* [ ] **slack-api-*-kotlin-extension** (Kotlin Extensions for Slack API Clients)
* [ ] **slack-app-backend** (The primitive layer of Bolt for Java)

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to the those rules.

### CODE REVIEW

File: slack-api-client/src/main/java/com/slack/api/methods/request/team/TeamInfoRequest.java [hunk 1]
```diff
@@ -13,4 +13,9 @@
      */
     private String token;
 
+    /**
+     * Id of the team to get info on, if omitted, will return information about the current team.
```
Comment (seratch) [inline slack-api-client/src/main/java/com/slack/api/methods/request/team/TeamInfoRequest.java:17]: We want to copy the latest version of the description in the API document as-is.
```suggestion
     * Team to get info on, if omitted, will return information about the current team. Will only return team that the authenticated token is allowed to see through external shared channels
```

Comment (seratch) [reply slack-api-client/src/main/java/com/slack/api/methods/request/team/TeamInfoRequest.java:17]: I know the description in the website can be changed in the future but in this case, the latter half should be helpful for developers.

Comment (lfbrandao) [reply slack-api-client/src/main/java/com/slack/api/methods/request/team/TeamInfoRequest.java]: Updated, thanks!

**Review by seratch — APPROVED** [review]

**Comment by seratch** [comment]
@lfbrandao Thanks for your quick work here! Looks great to me 👍 I will merge this PR once we see the CI builds successfully pass.

**Comment by lfbrandao** [comment]
wonderful, thanks @seratch!
