### PR TITLE
fix filename & title getting improperly defaulted in filesUploadV2

### LINKED ISSUE #1345: Uploading multiple files overrides filename
Uploading multiple files using the 'not mainly used for backwards compatibility' overrides filename of all `FilesUploadV2Request.UploadFile` objects passed to `com.slack.api.methods.impl.MethodsClientImpl#filesUploadV2` via `com.slack.api.methods.request.files.FilesUploadV2Request#uploadFiles`.

#### The Slack SDK version

`1.1.6` / model `1.40.3`

```
+--- com.slack.api:bolt:1.1.+ -> 1.1.6
|    +--- com.slack.api:slack-api-model:1.1.6 -> 1.40.3
|    +--- com.slack.api:slack-api-client:1.1.6 -> 1.40.3
|    |    +--- com.slack.api:slack-api-model:1.40.3 (*)
|    \--- com.slack.api:slack-app-backend:1.1.6
|         +--- com.slack.api:slack-api-model:1.1.6 -> 1.40.3 (*)
|         +--- com.slack.api:slack-api-client:1.1.6 -> 1.40.3 (*)
+--- com.slack.api:bolt-servlet:1.1.+ -> 1.1.6
|    +--- com.slack.api:slack-api-model:1.1.6 -> 1.40.3 (*)
|    +--- com.slack.api:slack-api-client:1.1.6 -> 1.40.3 (*)
|    +--- com.slack.api:slack-app-backend:1.1.6 (*)
|    \--- com.slack.api:bolt:1.1.6 (*)
+--- com.slack.api:bolt-jetty:1.1.+ -> 1.1.6
|    +--- com.slack.api:slack-api-model:1.1.6 -> 1.40.3 (*)
|    +--- com.slack.api:slack-api-client:1.1.6 -> 1.40.3 (*)
|    +--- com.slack.api:slack-app-backend:1.1.6 (*)
|    +--- com.slack.api:bolt:1.1.6 (*)
|    +--- com.slack.api:bolt-servlet:1.1.6 (*)
+--- com.slack.api:slack-api-client:1.+ -> 1.40.3 (*)
+--- com.slack.api:bolt:1.1.+ (n)
+--- com.slack.api:bolt-servlet:1.1.+ (n)
+--- com.slack.api:bolt-jetty:1.1.+ (n)
+--- com.slack.api:slack-api-client:1.+ (n)
+--- com.slack.api:bolt:1.1.+ -> 1.1.6
|    +--- com.slack.api:slack-api-model:1.1.6 -> 1.40.3
|    +--- com.slack.api:slack-api-client:1.1.6 -> 1.40.3
|    |    +--- com.slack.api:slack-api-model:1.40.3 (*)
|    \--- com.slack.api:slack-app-backend:1.1.6
|         +--- com.slack.api:slack-api-model:1.1.6 -> 1.40.3 (*)
|         +--- com.slack.api:slack-api-client:1.1.6 -> 1.40.3 (*)
+--- com.slack.api:bolt-servlet:1.1.+ -> 1.1.6
|    +--- com.slack.api:slack-api-model:1.1.6 -> 1.40.3 (*)
|    +--- com.slack.api:slack-api-client:1.1.6 -> 1.40.3 (*)
|    +--- com.slack.api:slack-app-backend:1.1.6 (*)
|    \--- com.slack.api:bolt:1.1.6 (*)
+--- com.slack.api:bolt-jetty:1.1.+ -> 1.1.6
|    +--- com.slack.api:slack-api-model:1.1.6 -> 1.40.3 (*)
|    +--- com.slack.api:slack-api-client:1.1.6 -> 1.40.3 (*)
|    +--- com.slack.api:slack-app-backend:1.1.6 (*)
|    +--- com.slack.api:bolt:1.1.6 (*)
|    +--- com.slack.api:bolt-servlet:1.1.6 (*)
+--- com.slack.api:slack-api-client:1.+ -> 1.40.3 (*)
+--- com.slack.api:bolt:1.1.+ -> 1.1.6
|    +--- com.slack.api:slack-api-model:1.1.6 -> 1.40.3
|    +--- com.slack.api:slack-api-client:1.1.6 -> 1.40.3
|    |    +--- com.slack.api:slack-api-model:1.40.3 (*)
|    \--- com.slack.api:slack-app-backend:1.1.6
|         +--- com.slack.api:slack-api-model:1.1.6 -> 1.40.3 (*)
|         +--- com.slack.api:slack-api-client:1.1.6 -> 1.40.3 (*)
+--- com.slack.api:bolt-servlet:1.1.+ -> 1.1.6
|    +--- com.slack.api:slack-api-model:1.1.6 -> 1.40.3 (*)
|    +--- com.slack.api:slack-api-client:1.1.6 -> 1.40.3 (*)
|    +--- com.slack.api:slack-app-backend:1.1.6 (*)
|    \--- com.slack.api:bolt:1.1.6 (*)
+--- com.slack.api:bolt-jetty:1.1.+ -> 1.1.6
|    +--- com.slack.api:slack-api-model:1.1.6 -> 1.40.3 (*)
|    +--- com.slack.api:slack-api-client:1.1.6 -> 1.40.3 (*)
|    +--- com.slack.api:slack-app-backend:1.1.6 (*)
|    +--- com.slack.api:bolt:1.1.6 (*)
|    +--- com.slack.api:bolt-servlet:1.1.6 (*)
+--- com.slack.api:slack-api-client:1.+ -> 1.40.3 (*)
+--- com.slack.api:bolt:1.1.+ -> 1.1.6
|    +--- com.slack.api:slack-api-model:1.1.6 -> 1.40.3
|    +--- com.slack.api:slack-api-client:1.1.6 -> 1.40.3
|    |    +--- com.slack.api:slack-api-model:1.40.3 (*)
|    \--- com.slack.api:slack-app-backend:1.1.6
|         +--- com.slack.api:slack-api-model:1.1.6 -> 1.40.3 (*)
|         +--- com.slack.api:slack-api-client:1.1.6 -> 1.40.3 (*)
+--- com.slack.api:bolt-servlet:1.1.+ -> 1.1.6
|    +--- com.slack.api:slack-api-model:1.1.6 -> 1.40.3 (*)
|    +--- com.slack.api:slack-api-client:1.1.6 -> 1.40.3 (*)
|    +--- com.slack.api:slack-app-backend:1.1.6 (*)
|    \--- com.slack.api:bolt:1.1.6 (*)
+--- com.slack.api:bolt-jetty:1.1.+ -> 1.1.6
|    +--- com.slack.api:slack-api-model:1.1.6 -> 1.40.3 (*)
|    +--- com.slack.api:slack-api-client:1.1.6 -> 1.40.3 (*)
|    +--- com.slack.api:slack-app-backend:1.1.6 (*)
|    +--- com.slack.api:bolt:1.1.6 (*)
|    +--- com.slack.api:bolt-servlet:1.1.6 (*)
+--- com.slack.api:slack-api-client:1.+ -> 1.40.3 (*)
```

#### Java Runtime version

(version-independent/this information is irrelevant)
```
openjdk version "21.0.4" 2024-07-16
OpenJDK Runtime Environment (build 21.0.4+7-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 21.0.4+7-Ubuntu-1ubuntu222.04, mixed mode, sharing)
```

#### OS info

(version-independent/this information is irrelevant)
```
#45~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 15 16:40:02 UTC 2
```

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., pom.xml/build.gradle))

1. attempt uploading any file using the `filesUploadV2` method (it doesn't matter if the `FilesUploadV2Request#filename` field is blank/null or set to any value)
2. observe the filename of all files being replaced with `Uploaded File` (if null was passed) or the passed `FilesUploadV2Request#filename`
3. you can bypass this issue by uploading one single file at a time, by using the fields commented with `(this is mainly for backward compatibility - using uploadFiles instead is recommended)`
4. inspect the source code (`com.slack.api.methods.impl.MethodsClientImpl`, line 2341) and confirm the error

#### Expected result:

The filenames don't get overridden

#### Actual result:

All filenames are replaced with one single value

### How to fix:

in `com.slack.api.methods.impl.MethodsClientImpl` on line 2341, replace the call to `req.getFilename()` with a call to `uploadFile.getFilename()` .
This seems to be a simple copy-paste error - though i think it might be useful to check the entire method for additional errors i might've overlooked.

### Requirements

Please make sure if this topic is specific to this SDK. For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you agree to those rules.

### PR DESCRIPTION
**Pull request by Cheos137**
fix filename & title getting improperly defaulted when uploading multiple files using MethodsClientImpl#filesUploadV2

fixes #1345

### Category (place an `x` in each of the `[ ]`)

* [ ] **bolt** (Bolt for Java)
* [ ] **bolt-{sub modules}** (Bolt for Java - optional modules)
* [x] **slack-api-client** (Slack API Clients)
* [ ] **slack-api-model** (Slack API Data Models)
* [ ] **slack-api-*-kotlin-extension** (Kotlin Extensions for Slack API Clients)
* [ ] **slack-app-backend** (The primitive layer of Bolt for Java)

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you agree to those rules.

### CODE REVIEW

**Comment by zimeg** [comment]
Hi @Cheos137! 👋  Thank you for taking the time to send in this PR and sign the CLA!

This logic is looking solid to me but [we might want to include a test](https://github.com/slackapi/java-slack-sdk/blob/71ed00d377ea5a65cc5412e1ca63e782b045d1b2/slack-api-client/src/test/java/test_with_remote_apis/methods/files_Test.java#L646) to ensure this behavior is correct and doesn't regress in future changes 🙏

**Comment by Cheos137** [comment]
cuz i suspect there might not have gone out a notification from it: yesterday i've added tests to this pr

File: slack-api-client/src/test/java/test_with_remote_apis/methods/files_Test.java [hunk 1]
```diff
@@ -1167,4 +1167,91 @@ public void filesUploadV2_manual_two_files() throws Exception {
...
+
+    @Test
+    public void issue1345_filesUploadV2_multiple() throws IOException, SlackApiException {
+        loadRandomChannelId();
+        MethodsClient slackMethods = slack.methods(userToken);
+
+        byte[] fileData = Files.readAllBytes(Paths.get("src/test/resources/sample.txt"));
+
+        // note: this test can be done using only one file as everything tested applies to each file individually - the only important thing is to use "uploadFiles" instead of direct values
+        FilesUploadV2Request.UploadFile uploadFile = FilesUploadV2Request.UploadFile.builder().filename("issue1345_test.txt").title("issue1345 test").fileData(fileData);
```
Comment (zimeg) [inline slack-api-client/src/test/java/test_with_remote_apis/methods/files_Test.java:1179]:
```suggestion
        FilesUploadV2Request.UploadFile uploadFile = FilesUploadV2Request.UploadFile.builder().filename("issue1345_test.txt").title("issue1345 test").fileData(fileData).build();
```

This seems to be causing [compilation errors](https://github.com/slackapi/java-slack-sdk/actions/runs/10402312991/job/28880285507?pr=1346#step:4:434) right now 🤔

**Review by zimeg — COMMENTED** [review]
Thanks a ton for adding the tests! Once these are passing I think the PR will be in a solid spot 🙏

File: slack-api-client/src/test/java/test_with_remote_apis/methods/files_Test.java (hunk 1 above)
Comment (Cheos137) [reply slack-api-client/src/test/java/test_with_remote_apis/methods/files_Test.java]: whoops, forgot calling `#build` on each of these builders

Comment (Cheos137) [reply slack-api-client/src/test/java/test_with_remote_apis/methods/files_Test.java]: should be fixed now

File: slack-api-client/src/test/java/test_with_remote_apis/methods/files_Test.java [hunk 2]
```diff
@@ -1167,4 +1167,91 @@ public void filesUploadV2_manual_two_files() throws Exception {
...
+
+    @Test
+    public void issue1345_filesUploadV2_multiple_no_filename_no_title_file() throws IOException, SlackApiException {
+        loadRandomChannelId();
+        MethodsClient slackMethods = slack.methods(userToken);
+
+        File file = new File("src/test/resources/sample.txt");
+
+        // note: this test can be done using only one file as everything tested applies to each file individually - the only important thing is to use "uploadFiles" instead of direct values
+        FilesUploadV2Request.UploadFile uploadFile = FilesUploadV2Request.UploadFile.builder().file(fileData).build();
```
Comment (zimeg) [inline slack-api-client/src/test/java/test_with_remote_apis/methods/files_Test.java:1230]:
```suggestion
        FilesUploadV2Request.UploadFile uploadFile = FilesUploadV2Request.UploadFile.builder().file(file).build();
```

One other change to test! 🙏

File: slack-api-client/src/test/java/test_with_remote_apis/methods/files_Test.java [hunk 3]
```diff
@@ -1167,4 +1167,91 @@ public void filesUploadV2_manual_two_files() throws Exception {
...
+        FilesUploadV2Response response = slackMethods.filesUploadV2(r -> r.uploadFiles(List.of(uploadFile)));
+
+        assertThat(response.getError(), is(nullValue()));
+        // filename defaults to "Uploaded file", which will be converted by slack servers to be lowercase only, contain no special characters but underscores, dots and dashes, etc.
+        assertThat(response.getFiles().get(0).getName(), is(file.getName()));
+        // title should be unaffected if it has a value set
+        assertThat(response.getFiles().get(0).getTitle(), is(file.getName()));
```
Comment (zimeg) [inline slack-api-client/src/test/java/test_with_remote_apis/methods/files_Test.java:1237]: Should we hardcode these values in the tests or is the file being changed sometimes? 🤔

**Review by zimeg — COMMENTED** [review]
This is looking solid! I did leave one question about the defaults being tested that I'm unsure of myself- let me know if setting specific strings seems right 🧵 👀

File: slack-api-client/src/test/java/test_with_remote_apis/methods/files_Test.java (hunk 3 above)
Comment (Cheos137) [reply slack-api-client/src/test/java/test_with_remote_apis/methods/files_Test.java:1237]: i don't think the file will ever get changed here (as it doesn't really matter what file is uploaded in these 4 tests)
thus, i think hardcoding would be an option if you think `java.io.File#getName` shouldn't be relied on here

Comment (zimeg) [reply slack-api-client/src/test/java/test_with_remote_apis/methods/files_Test.java:1237]: I'm keen to trust `java.io.File` here but also think it can be more clear when hardcoded!

File: slack-api-client/src/test/java/test_with_remote_apis/methods/files_Test.java [hunk 4]
```diff
@@ -1167,4 +1167,91 @@ public void filesUploadV2_manual_two_files() throws Exception {
...
+    @Test
+    public void issue1345_filesUploadV2_multiple() throws IOException, SlackApiException {
+        loadRandomChannelId();
+        MethodsClient slackMethods = slack.methods(userToken);
+
+        byte[] fileData = Files.readAllBytes(Paths.get("src/test/resources/sample.txt"));
+
+        // note: this test can be done using only one file as everything tested applies to each file individually - the only important thing is to use "uploadFiles" instead of direct values
+        FilesUploadV2Request.UploadFile uploadFile = FilesUploadV2Request.UploadFile.builder().filename("issue1345_test.txt").title("issue1345 test").fileData(fileData).build();
+        FilesUploadV2Response response = slackMethods.filesUploadV2(r -> r.uploadFiles(List.of(uploadFile)));
```
Comment (zimeg) [inline slack-api-client/src/test/java/test_with_remote_apis/methods/files_Test.java:1180]:
```suggestion
        FilesUploadV2Response response = slackMethods.filesUploadV2(r -> r.uploadFiles(Arrays.asList(uploadFile)));
```

I believe we'll need an approach [compatible with Java 8](https://github.com/slackapi/java-slack-sdk/actions/runs/10438828674/job/28907172494?pr=1346#step:4:473) here 🤔

**Review by zimeg — COMMENTED** [review]
📝 🎶 A few more notes, but thank you for the fast fixes already!

File: slack-api-client/src/test/java/test_with_remote_apis/methods/files_Test.java (hunk 3 above)
Comment (Cheos137) [reply slack-api-client/src/test/java/test_with_remote_apis/methods/files_Test.java]: using hardcoded constants now

**Review by seratch — APPROVED** [review]
Thank you so much for fixing this! Looks great to me 👍
