### PR TITLE
Fix #1426 IllegalStateException when deserializing message using conversations.history

### LINKED ISSUE #1426: IllegalStateException when deserializing message using conversation.history
Using conversations.history, we are getting exceptions when the slack sdk attempts to deserialize a customer's message history.

The issue is in the groups field inside the first attachment of the first file in the 169th message of the messages array in the API response is expected to be an array in your sdk but turned out to be an object.

-------

Got an exception while calling conversations.history API (team: ****, error: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 164106 path $.messages[169].attachments[0].files[0].groups See https://github.com/google/gson/blob/main/Troubleshooting.md#unexpected-json-structure)

```
 j.l.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 164106 path $.messages[169].attachments[0].files[0].groups
See https://github.com/google/gson/blob/main/Troubleshooting.md#unexpected-json-structure
	at c.g.g.s.JsonReader.unexpectedTokenError(JsonReader.java:1768)
	at c.g.g.s.JsonReader.beginArray(JsonReader.java:430)
	at c.g.g.i.b.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:81)
	at c.g.g.i.b.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:59)
	at c.g.g.i.b.ReflectiveTypeAdapterFactory$2.readIntoField(ReflectiveTypeAdapterFactory.java:267)
	at c.g.g.i.b.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:558)
	at c.g.g.i.b.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:516)
	... 33 common frames omitted
Wrapped by: c.g.g.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 164106 path $.messages[169].attachments[0].files[0].groups
See https://github.com/google/gson/blob/main/Troubleshooting.md#unexpected-json-structure
	at c.g.g.i.b.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:520)
	at c.g.g.i.b.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at c.g.g.i.b.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:83)
	at c.g.g.i.b.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:59)
	at c.g.g.i.b.ReflectiveTypeAdapterFactory$2.readIntoField(ReflectiveTypeAdapterFactory.java:267)
	at c.g.g.i.b.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:558)
	at c.g.g.i.b.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:516)
	at c.g.g.i.b.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at c.g.g.i.b.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:83)
	at c.g.g.i.b.Collect...

```

### PR DESCRIPTION
**Pull request by seratch**
This pull request resolves #1426 

### Category (place an `x` in each of the `[ ]`)

* [ ] **bolt** (Bolt for Java)
* [ ] **bolt-{sub modules}** (Bolt for Java - optional modules)
* [x] **slack-api-client** (Slack API Clients)
* [x] **slack-api-model** (Slack API Data Models)
* [ ] **slack-api-*-kotlin-extension** (Kotlin Extensions for Slack API Clients)
* [ ] **slack-app-backend** (The primitive layer of Bolt for Java)

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you agree to those rules.

### CODE REVIEW

File: slack-api-model/src/main/java/com/slack/api/util/json/GsonFileFactory.java [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+
+import com.google.gson.*;
+import com.slack.api.model.File;
+
+import java.lang.reflect.Type;
+
+public class GsonFileFactory implements JsonDeserializer<File>, JsonSerializer<File> {
+
+    // This is just a workaround to customize Gson library behavior
+    // You don't need to edit this class at all
```
Comment (WilliamBergamin) [inline slack-api-model/src/main/java/com/slack/api/util/json/GsonFileFactory.java:11]: Not sure I understand this comment, do we still need it?

**Review by WilliamBergamin — APPROVED** [review]
This seems good 💯 

Just for my own understanding, if the `groups` field is not an array then its content gets removed and if `shares.public` or `shares.private` are present then their `reply_users` fields are not arrays they also get removed?

File: slack-api-model/src/main/java/com/slack/api/util/json/GsonFileFactory.java (hunk 1 above)
Comment (seratch) [reply slack-api-model/src/main/java/com/slack/api/util/json/GsonFileFactory.java:11]: As mentioned below, if you run `context.deserialize(jsonObject, File.class);` within the deserialize method, it results in StackOverflowError because the same method is associated with the File.class. To let gson mechansim to run a different auto-binding process without stack overflow, I've added this sub class. This is internal hidden class, so you can rename it whenever you want to do so. Also, if you find a better solution to achive the same, please feel free to change this part. It won't be a breaking change because this class and the the code using it are hidden from users.
