### PR TITLE
Fix #1161 Internal thread resources are not shut down when calling SlackConfig#close()

### LINKED ISSUE #1161: Internal thread resources are not shut down when calling SlackConfig#close()
Fix Tomcat memory leak in https://github.com/slackapi/java-slack-sdk/blob/144b42eeb4f3bf3f6ed898979bb203efe4bd2342/slack-api-client/src/main/java/com/slack/api/rate_limits/metrics/impl/BaseMemoryMetricsDatastore.java#L77

#### The Slack SDK version

com.slack.api:slack-api-client:1.29.2

#### Java Runtime version

17.0.7

#### Tomcat version

9.0.75

#### Steps to reproduce:

1. Initialise `Slack.getInstance()`
2. Deploy on Tomcat
3. Redeploy on Tomcat

#### Expected result:

I would expect all threads started by `Slack` (`SlackConfig`) to terminate properly once the application has been redeployed on Tomcat. Although since the `MaintenanceJob` is submitted to the `ScheduledExecutorService` (in `BaseMemoryMetricsDatastore`) before you get the chance to disable stats in `SlackConfig`, it's not possible to disable this job. 

#### Actual result:

Since there is no way to get a reference to a `ScheduledFuture<?>`, after submitting a `MaintenanceJob` to the `ScheduledExecutorService`, it's not possible to properly shutdown the `ScheduledExecutorService`. This causes a memory leak in Tomcat, so the whole tomcat service needs to be restarted on application redeploy.

Besides this, on `Slack.close()`, the `ScheduledExecutorService` never gets shutdown, since there is no reference to them in `ThreadPools.ALL_DEFAULT`. Although for this to even work, the `ScheduledFuture<?>` jobs need to be cancelled. For this to work the fields here https://github.com/slackapi/java-slack-sdk/blob/144b42eeb4f3bf3f6ed898979bb203efe4bd2342/slack-api-client/src/main/java/com/slack/api/SlackConfig.java#L294 should not be initialised by default, but rather need to be set by the developer, after the https://github.com/slackapi/java-slack-sdk/blob/144b42eeb4f3bf3f6ed898979bb203efe4bd2342/slack-api-client/src/main/java/com/slack/api/SlackConfig.java#L284 `statsEnabled` has been set to false.

```
17-May-2023 16:44:32.199 WARNING [RMI TCP Connection(6)-127.0.0.1] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [Gradle___dk_onlinefundraising___data_receiver_war] appears to have started a thread named [slack-api-metrics:13e0ca29-worker-54] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@17.0.7/jdk.internal.misc.Unsafe.park(Native Method)
 java.base@17.0.7/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
 java.base@17.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1672)
 java.base@17.0.7/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
 java.base@17.0.7/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
 java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
 java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122)
 java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 java.base@17.0.7/java.lang.Thread.run(Thread.java:833)
17-May-2023 16:44:32.200 WARNING [RMI TCP Connection(6)-127.0.0.1] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [Gradle___dk_onlinefundraising___data_receiver_war] appears to have started a thread named [slack-api-metrics:2a4b02cd-worker-55] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@17.0.7/jdk.internal.misc.Unsafe.park(Native Method)
 java.base@17.0.7/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
 java.base@17.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1672)
 java.base@17.0.7/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
 java.base@17.0.7/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
 java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
 java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122)
 java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 java.base@17.0.7/java.lang.Thread.run(Thread.java:833)
17-May-2023 16:44:32.201 WARNING [RMI TCP Connection(6)-127.0.0.1] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [Gradle___dk_onlinefundraising___data_receiver_war] appears to have started a thread named [slack-api-metrics:72edf51c-worker-56] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@17.0.7/jdk.internal.misc.Unsafe.park(Native Method)
 java.base@17.0.7/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
 java.base@17.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1672)
 java.base@17.0.7/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
 java.base@17.0.7/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
 java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
 java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122)
 java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 java.base@17.0.7/java.lang.Thread.run(Thread.java:833)
17-May-2023 16:44:32.202 WARNING [RMI TCP Connection(6)-127.0.0.1] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [Gradle___dk_onlinefundraising___data_receiver_war] appears to have started a thread named [slack-api-metrics:264b6ddb-worker-57] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@17.0.7/jdk.internal.misc.Unsafe.park(Native Method)
 java.base@17.0.7/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
 java.base@17.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1672)
 java.base@17.0.7/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
 java.base@17.0.7/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
 java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
 java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122)
 java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 java.base@17.0.7/java.lang.Thread.run(Thread.java:833)
17-May-2023 16:44:32.202 WARNING [RMI TCP Connection(6)-127.0.0.1] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [Gradle___dk_onlinefundraising___data_receiver_war] appears to have started a thread named [slack-api-metrics:94f9b1b-worker-58] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@17.0.7/jdk.internal.misc.Unsafe.park(Native Method)
 java.base@17.0.7/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
 java.base@17.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1672)
 java.base@17.0.7/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
 java.base@17.0.7/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
 java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
 java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122)
 java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 java.base@17.0.7/java.lang.Thread.run(Thread.java:833)
17-May-2023 16:44:32.203 WARNING [RMI TCP Connection(6)-127.0.0.1] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [Gradle___dk_onlinefundraising___data_receiver_war] appears to have started a thread named [slack-api-metrics:4a19edba-worker-59] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@17.0.7/jdk.internal.misc.Unsafe.park(Native Method)
 java.base@17.0.7/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
 java.base@17.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1672)
 java.base@17.0.7/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
 java.base@17.0.7/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
 java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
 java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122)
 java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 java.base@17.0.7/java.lang.Thread.run(Thread.java:833)
```

### PR DESCRIPTION
**Pull request by seratch**
This pull request resolves #1161 

### Category (place an `x` in each of the `[ ]`)

* [ ] **bolt** (Bolt for Java)
* [ ] **bolt-{sub modules}** (Bolt for Java - optional modules)
* [x] **slack-api-client** (Slack API Clients)
* [ ] **slack-api-model** (Slack API Data Models)
* [ ] **slack-api-*-kotlin-extension** (Kotlin Extensions for Slack API Clients)
* [ ] **slack-app-backend** (The primitive layer of Bolt for Java)

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you agree to those rules.

### CODE REVIEW

File: slack-api-client/src/main/java/com/slack/api/SlackConfig.java [hunk 1]
```diff
@@ -384,8 +408,17 @@ public void synchronizeLibraryMaintainerMode() {
...
+        this.getAuditConfig().setStatsEnabled(false);
+        this.getSCIMConfig().setStatsEnabled(false);
+        this.getSCIM2Config().setStatsEnabled(false);
+        this.synchronizeMetricsDatabases();
+
+        // Clear the internal thread pools for asynchronous API calls
         com.slack.api.methods.impl.ThreadPools.shutdownAll(methodsConfig);
         com.slack.api.audit.impl.ThreadPools.shutdownAll(auditConfig);
         com.slack.api.scim.impl.ThreadPools.shutdownAll(sCIMConfig);
+        com.slack.api.scim2.impl.ThreadPools.shutdownAll(sCIM2Config);
```
Comment (seratch) [inline slack-api-client/src/main/java/com/slack/api/SlackConfig.java:422]: This is a bug in https://github.com/slackapi/java-slack-sdk/pull/1158
