### PR TITLE
Fix #933 by adjusting the internals of smart rate limiter

### LINKED ISSUE #933: 100% CPU usage when working with a high number of workspaces
We noticed a flaw in the Java SDK. When interacting with a large number of workspaces, the rate-limiting algorithm consume 100% CPU. After profiling our server we noticed that 96% of the CPU is spent on `BaseMemoryMetricsDataStore$MaintenanceJob.run()`. Particularly the methods `updateCurrentQueueSize` and `updateNumberOfLastMinuteRequests`. I believe this is because our app deals with a large number of workspaces (~8,000) and the maintenance job runs every [50ms](https://github.com/slackapi/java-slack-sdk/blob/main/slack-api-client/src/main/java/com/slack/api/rate_limits/metrics/impl/BaseMemoryMetricsDatastore.java#L45).

As a temporary solution, we are considering turning off stats on `MethodConfig`.

Any other suggestion to mitigate/fix the issue? 

#### The Slack SDK version

1.18.0

#### Java Runtime version

(Paste the output of `java -version`)

#### OS info

Linux

#### Steps to reproduce:

Create an app that unfurl links from ~8,000 workspaces.

#### Expected result:

Reasonable CPU usage.

#### Actual result:

100% CPU usage after running for 16h.
The CPU usage progressively increases until the server restarts.

### PR DESCRIPTION
**Pull request by seratch**
This pull request resolves #933 by improving the internals of API clients' smart rate limiter. The key changes are:

* Changed the interval of the background job from 50 milliseconds to 1,000 milliseconds (verified that there is almost zero downsize by changing this)
* Enabled the maintenance job to skip updating metrics data if a team_id does not have any updates since the previous maintenance
* Changed to disable the background thread If the `statsEnabled` is false
* Added traceMode to the background job for easier debugging on the SDK maintainer side (disabled by default)

### Category (place an `x` in each of the `[ ]`)

* [ ] **bolt** (Bolt for Java)
* [ ] **bolt-{sub modules}** (Bolt for Java - optional modules)
* [x] **slack-api-client** (Slack API Clients)
* [ ] **slack-api-model** (Slack API Data Models)
* [ ] **slack-api-*-kotlin-extension** (Kotlin Extensions for Slack API Clients)
* [ ] **slack-app-backend** (The primitive layer of Bolt for Java)

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to the those rules.

### CODE REVIEW

File: slack-api-client/src/main/java/com/slack/api/SlackConfig.java [hunk 1]
```diff
@@ -234,17 +234,28 @@ public void synchronizeExecutorServiceProviders() {
         if (!methodsConfig.equals(MethodsConfig.DEFAULT_SINGLETON)
                 && !methodsConfig.getExecutorServiceProvider().equals(executorServiceProvider)) {
             methodsConfig.setExecutorServiceProvider(executorServiceProvider);
-            methodsConfig.getMetricsDatastore().setExecutorServiceProvider(executorServiceProvider);
+            if (methodsConfig.isStatsEnabled()) {
```
Comment (seratch) [inline slack-api-client/src/main/java/com/slack/api/SlackConfig.java:237]: If this flag is set to false, ExecutorServiceProvider won't be used.

File: slack-api-client/src/main/java/com/slack/api/SlackConfig.java [hunk 2]
```diff
@@ -234,17 +234,28 @@ public void synchronizeExecutorServiceProviders() {
...
         }
         if (!sCIMConfig.equals(SCIMConfig.DEFAULT_SINGLETON)
                 && !sCIMConfig.getExecutorServiceProvider().equals(executorServiceProvider)) {
             sCIMConfig.setExecutorServiceProvider(executorServiceProvider);
-            sCIMConfig.getMetricsDatastore().setExecutorServiceProvider(executorServiceProvider);
+            if (sCIMConfig.isStatsEnabled()) {
+                sCIMConfig.getMetricsDatastore().setExecutorServiceProvider(executorServiceProvider);
+            }
+        }
+        if (this.isLibraryMaintainerMode()) {
```
Comment (seratch) [inline slack-api-client/src/main/java/com/slack/api/SlackConfig.java:255]: This is the debug mode for this SDK maintainers

File: slack-api-client/src/main/java/com/slack/api/audit/metrics/MemoryMetricsDatastore.java [hunk 3]
```diff
@@ -12,6 +14,30 @@ public MemoryMetricsDatastore(int numberOfNodes) {
...
+    public MemoryMetricsDatastore(
+            int numberOfNodes,
+            boolean cleanerEnabled
+    ) {
+        super(numberOfNodes, DaemonThreadExecutorServiceProvider.getInstance(), cleanerEnabled, DEFAULT_CLEANER_EXECUTION_INTERVAL_MILLISECONDS);
+    }
+
+    public MemoryMetricsDatastore(
+            int numberOfNodes,
+            boolean cleanerEnabled,
```
Comment (seratch) [inline slack-api-client/src/main/java/com/slack/api/audit/metrics/MemoryMetricsDatastore.java:26]: Enabling developers to customize these settings

File: slack-api-client/src/main/java/com/slack/api/methods/metrics/RedisMetricsDatastore.java [hunk 4]
```diff
@@ -13,8 +14,32 @@ public RedisMetricsDatastore(String appName, JedisPool jedisPool) {
...
+        super(appName, jedisPool, executorServiceProvider, cleanerEnabled, cleanerExecutionIntervalMilliseconds);
+    }
+
     @Override
     public RateLimitQueue<AsyncExecutionSupplier<? extends SlackApiResponse>, AsyncRateLimitQueue.Message> getRateLimitQueue(String executorName, String teamId) {
         return AsyncRateLimitQueue.get(executorName, teamId);
     }
+
+    @Override
+    protected String getMetricsType() {
```
Comment (seratch) [inline slack-api-client/src/main/java/com/slack/api/methods/metrics/RedisMetricsDatastore.java:42]: Added this to improve traceMode logging

File: slack-api-client/src/main/java/com/slack/api/rate_limits/metrics/impl/BaseMemoryMetricsDatastore.java [hunk 5]
```diff
@@ -94,14 +123,27 @@ public ExecutorServiceProvider getExecutorServiceProvider() {
     @Override
     public void setExecutorServiceProvider(ExecutorServiceProvider executorServiceProvider) {
         this.executorServiceProvider = executorServiceProvider;
-        initializeCleanerExecutor();
+        if (this.cleanerEnabled) {
+            initializeCleanerExecutor();
```
Comment (seratch) [inline slack-api-client/src/main/java/com/slack/api/rate_limits/metrics/impl/BaseMemoryMetricsDatastore.java:127]: Skip the initialization (= starting a scheduled async code execution) if cleanerEnabled is false

File: slack-api-client/src/main/java/com/slack/api/rate_limits/metrics/impl/BaseMemoryMetricsDatastore.java [hunk 6]
```diff
@@ -295,15 +340,22 @@ private LastMinuteRequests getOrCreateLastMinuteRequests(String executorName, St
...
     // -----------------------------------------------------------
 
-    private static class MaintenanceJob implements Runnable {
+    @Slf4j
+    public static class MaintenanceJob implements Runnable {
         private final BaseMemoryMetricsDatastore store;
+        private long lastExecutionTimestampMillis;
 
-        MaintenanceJob(BaseMemoryMetricsDatastore store) {
+        public MaintenanceJob(BaseMemoryMetricsDatastore store) {
```
Comment (seratch) [inline slack-api-client/src/main/java/com/slack/api/rate_limits/metrics/impl/BaseMemoryMetricsDatastore.java:348]: Changed the access modifier for easier testing

File: slack-api-client/src/main/java/com/slack/api/rate_limits/metrics/impl/BaseMemoryMetricsDatastore.java [hunk 7]
```diff
@@ -314,9 +366,30 @@ public void run() {
...
+                    );
+                }
                 for (ConcurrentMap.Entry<String, LiveRequestStats> team : executor.getValue().entrySet()) {
                     String teamId = team.getKey();
                     LiveRequestStats stats = team.getValue();
+                    if (stats == null) {
+                        continue;
+                    }
+                    if (stats.getLastRequestTimestampMillis() != null
+                            && stats.getLastRequestTimestampMillis() <= this.lastExecutionTimestampMillis) {
```
Comment (seratch) [inline slack-api-client/src/main/java/com/slack/api/rate_limits/metrics/impl/BaseMemoryMetricsDatastore.java:384]: If there is no new request since the previous `run()` method execution, we can safely skip the following operations here.

File: slack-api-client/src/main/java/com/slack/api/rate_limits/metrics/impl/BaseMemoryMetricsDatastore.java [hunk 8]
```diff
@@ -340,7 +413,13 @@ public void run() {
                     }
                 }
             }
+
+            this.lastExecutionTimestampMillis = System.currentTimeMillis();
```
Comment (seratch) [inline slack-api-client/src/main/java/com/slack/api/rate_limits/metrics/impl/BaseMemoryMetricsDatastore.java:417]: Update the last execution time as this was successful

File: slack-api-client/src/test/java/test_locally/api/methods/metrics/RedisMetricsDatastoreTest.java [hunk 9]
```diff
@@ -106,8 +106,8 @@ public void increment() {
     public void threadGroupName() {
         RedisMetricsDatastore datastore1 = new RedisMetricsDatastore("app1", jedisPool);
         RedisMetricsDatastore datastore2 = new RedisMetricsDatastore("app2", jedisPool);
-        assertEquals("slack-methods-metrics-redis:app1", datastore1.getThreadGroupName());
-        assertEquals("slack-methods-metrics-redis:app2", datastore2.getThreadGroupName());
+        assertEquals("slack-api-metrics:app1", datastore1.getThreadGroupName());
```
Comment (seratch) [inline slack-api-client/src/test/java/test_locally/api/methods/metrics/RedisMetricsDatastoreTest.java:109]: Simplified -- no side effects on the user side

File: slack-api-client/src/test/java/test_locally/api/rate_limits/MemoryMaintenanceJobTest.java [hunk 10]
```diff
@@ -0,0 +1,69 @@
...
+                }
+
+                // All the teams are marked as done
+                {
+                    long before = System.currentTimeMillis();
+                    job.run();
+                    long spentMillis = System.currentTimeMillis() - before;
+                    log.info("Second execution: {} ms", spentMillis);
+                    assertThat(spentMillis, is(lessThan(store.isTraceMode() ? 150L : 30L)));
+                    assertThat(spentMillis, is(lessThanOrEqualTo(firstSpentTime)));
```
Comment (seratch) [inline slack-api-client/src/test/java/test_locally/api/rate_limits/MemoryMaintenanceJobTest.java:62]: The second one can skip all the teams - so the performance must be far better

**Comment by seratch** [comment]
This should be good to go now. Let me merge this PR and release a new version including the fix.
